### ISSUE TITLE
Multiple points on the same line are behaves like one single point

### ISSUE THREAD

**Issue by erazmerita** [Azure-Samples/azure-maps-bring-data-into-view-control#1]
> Please provide us with the following information:
> ---------------------------------------------------------------

### Minimal steps to reproduce
Create two points with the same value for latitude or longitude.
Sample data:
[{
  latitude: 48,
  longitude: 8
},
{
  latitude: 48.1,
  longitude: 8
}]

Observed:
Is going in this block of code:
![image](https://user-images.githubusercontent.com/60657830/184110254-f6a1f7d9-8d8f-402f-8a46-dd25b179d201.png)
and after zoom points are not visible on the map:
![image](https://user-images.githubusercontent.com/60657830/184110833-972b3599-5e49-4ea1-a4dd-1c552e5df40e.png)

Expected:
Points should be visible on the map.

My work around was to to replace or (||) with and (&&) in if statement.

Thank you,
Eugeniu

**Comment by rbrundritt** [comment]
Thanks for the feedback. This has been fixed in version 0.0.3.
